language: ruby
cache: bundler
rvm: 2.1.2
addons:
  postgresql: '9.3'
  code_climate:
    repo_token:
      secure: F966KKnRQpViEba94dM3IejkYWgOvkyCtpnHFZdhaj73Wjuo4SKk/B1lIGqb4jEMmyGTGPY2aTJ5oxgdT3Y/9aGHZtRD69/MXNPORV6NrAWdV2V+AhMRrqG0CyERgwpgXPW5VLmJEL7JoCWr8d5ot/jsqarpLMe8KUH9N/OugBs=
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- RACK_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: N09bigi+HA1anL8/KXpUb7T3CkaaT6jdUxsKv8Wy9VhAJUoywWY9yhOGAo+eigKYn06mhc+ufKmqbiMq1m3Py7Sz3jJz1mIEiZcBSW2r/sveJ7jKVultUjiD+ZbQLKEViwER6qMpLkRkwdmszPNADvRtAdjoWg8jNO6HDRLNhGw=
  app: young-lowlands-3367
  strategy: git
