language: ruby
cache: bundler
rvm:
  2.1.2
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 9595b79d5ee97c26d5cc6b00298fb63b395dfdf6663faa1dfbfaa6629bacdbaf
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RACK_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake